### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by lysnikolaou** [rgommers/scipy#143]
### Describe your issue.

After successfully rebuilding scipy with scipy/scipy#18247 merged, the tests fail cause a symbol can't be found in the cython lapack dynamic library object. I'm attaching the full error below.

<details>
<summary>Here's my system's configuration</summary>
```python3
>>> import scipy;scipy.show_config()
/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/__config__.py:140: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "x86_64-apple-darwin13.4.0-clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.33",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "x86_64-apple-darwin13.4.0-clang++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "11.3.0",
      "commands": "/Users/lysnikolaou/anaconda3/envs/scipy-dev/bin/x86_64-apple-darwin13.4.0-gfortran"
    },
    "pythran": {
      "version": "0.12.1",
      "include directory": "../../../../anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "OpenBLAS",
      "found": true,
      "version": "0.3.21",
      "detection method": "cmake",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "OpenBLAS",
      "found": true,
      "version": "0.3.21",
      "detection method": "cmake",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/Users/lysnikolaou/anaconda3/envs/scipy-dev/bin/python3.10",
    "version": "3.10"
  }
}
```
</details>

### Reproducing Code Example

```python
import scipy.linalg.blas
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 218, in <module>
    from ._matfuncs import *
  File "/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 19, in <module>
    from ._matfuncs_expm import pick_pade_structure, pade_UV_calc
  File "scipy/linalg/_matfuncs_expm.pyx", line 1, in init scipy.linalg._matfuncs_expm
ImportError: dlopen(/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/cython_lapack.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_ssyconvf_'
```

### SciPy/NumPy/Python version information

Scipy: 1.11.0.dev0+0.f8f18ef, Numpy1.24.2, Python 3.10.10

**Comment by rgommers** [comment]
I can reproduce this now on macOS. On macOS, CI fails with `_ssyconvf_` missing for both the Meson and `setup.py` based builds. On Windows, we see a missing `ssyconvf_` in the Meson build (note, no `_` prefix) in CI, while the `setup.py` builds on Azure all pass. Those (Meson vs. setup.py on Windows) are using different OpenBLAS builds, so that may have something to do with it. 

Cython 0.29.33 contains another bug where relative imports fail in combination with depfile support, which Meson 1.0 asks for. In combination with Meson 0.64.1 the build completes - so that's the winning combo for now. More tomorrow.

**Comment by rgommers** [comment]
This is an odd issue. The cause seems to be that `ssyconvf` is a local symbol in `libopenblas` on macOS, while the other `*syconvf` symbols are global. On Linux it's a normal global symbol.

Here is what it looks like on macOS for me (`libopenblas` 0.3.21 from conda-forge):
```
% objdump -t /Users/rgommers/mambaforge/envs/scipy-dev/lib/libopenblas.0.dylib | rg syconvf
00000000002e97e0 l     F __TEXT,__text _ssyconvf_
0000000000547130 g     F __TEXT,__text _csyconvf_
00000000005477f0 g     F __TEXT,__text _csyconvf_rook_
00000000003f7490 g     F __TEXT,__text _dsyconvf_
00000000003f7aa0 g     F __TEXT,__text _dsyconvf_rook_
00000000002e9df0 g     F __TEXT,__text _ssyconvf_rook_
00000000006845f0 g     F __TEXT,__text _zsyconvf_
0000000000684cb0 g     F __TEXT,__text _zsyconvf_rook_

% nm -gU /Users/rgommers/mambaforge/envs/scipy-dev/lib/libopenblas.0.dylib | rg syconvf    
0000000000547130 T _csyconvf_
00000000005477f0 T _csyconvf_rook_
00000000003f7490 T _dsyconvf_
00000000003f7aa0 T _dsyconvf_rook_
00000000002e9df0 T _ssyconvf_rook_
00000000006845f0 T _zsyconvf_
0000000000684cb0 T _zsyconvf_rook_
```

On Linux there's no difference between `ssyconvf` and `other `*ssyconvf` symbols:

<details>

```
$ nm -gD /home/rgommers/mambaforge/envs/scipy-dev/lib/libopenblas.so.0 | rg syconvf
0000000001c00930 T csyconvf_
0000000001c010b0 T csyconvf_rook_
0000000001a483f0 T dsyconvf_
0000000001a48b50 T dsyconvf_rook_
00000000018fcd00 T ssyconvf_
00000000018fd460 T ssyconvf_rook_
0000000001da1880 T zsyconvf_
0000000001da20a0 T zsyconvf_rook_

$ objdump -t /home/rgommers/mambaforge/envs/scipy-dev/lib/libopenblas.so.0 | rg syconvf
0000000000000000 l    df *ABS*  0000000000000000              ssyconvf.f
0000000000000000 l    df *ABS*  0000000000000000              ssyconvf_rook.f
0000000000000000 l    df *ABS*  0000000000000000              dsyconvf.f
0000000000000000 l    df *ABS*  0000000000000000              dsyconvf_rook.f
0000000000000000 l    df *ABS*  0000000000000000              csyconvf.f
0000000000000000 l    df *ABS*  0000000000000000              csyconvf_rook.f
0000000000000000 l    df *ABS*  0000000000000000              zsyconvf.f
0000000000000000 l    df *ABS*  0000000000000000              zsyconvf_rook.f
00000000018fd460 g     F .text  00000000000008b4              ssyconvf_rook_
0000000001da1880 g     F .text  0000000000000813              zsyconvf_
0000000001c00930 g     F .text  000000000000077d              csyconvf_
0000000001a48b50 g     F .text  00000000000008b4              dsyconvf_rook_
0000000001c010b0 g     F .text  0000000000000905              csyconvf_rook_
0000000001a483f0 g     F .text  0000000000000755              dsyconvf_
0000000001da20a0 g     F .text  00000000000009a4              zsyconvf_rook_
00000000018fcd00 g     F .text  0000000000000755              ssyconvf_
```

</details>

That doesn't yet explain why, or why this problem doesn't cause an issue in our `f2py` bindings, but it looks like a bug in OpenBLAS. I'll have a look at what causes this.

**Comment by rgommers** [comment]
@lysnikolaou I think https://github.com/xianyi/OpenBLAS/pull/3994 fixes the problem. We can't use this routine until that fix is available in the minimum OpenBLAS version that we support - which will take a year at the very least.

**Comment by lysnikolaou** [comment]
Got it. So we don't wrap this for now.

Thanks for the support!

**Comment by rgommers** [comment]
Guess we can close this now:)
